name: ISW2 Prediction

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    name: Test on JDK 24
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn -B test